---
title: "Template"
subtitle: "SUBTITLE"
author: "AUTHORS"
date: "`r format(Sys.Date(), '%d %b %Y')`"
output:
  html_document: 
    df_print: paged
    number_sections: yes
    toc: yes
    toc_float: true
    toc_depth: 3
    code_folding: show
editor_options:
  chunk_output_type: inline
---

```{r setup, include = TRUE, message=FALSE}
# setup
library(dplyr)
library(ggplot2)
source(file.path("scripts", "functions.R"))
```

# $\LaTeX$ Math

This is just markdown that can include latex math.

$$
\begin{align}
\dot{x} & = \sigma(y-x) \\
\dot{y} & = \rho x - y - xz \\
\dot{z} & = -\beta z + xy
\end{align}
$$

# System Info

```{r}
# session info
sessionInfo()
```


# Custom Function

```{r}
# custom function from scripts/functions.R loaded in setup
test_add(2,5)
```

# Data

```{r}
# data
parabola <- 
  data_frame(
    x = -20:20,
    err = rnorm(n = length(x), sd = 5),
    y = (x + err)^2
  ) 
parabola
```

# Plot

```{r, fig.width=6, fig.height=4}
parabola %>% 
  ggplot() + 
  aes(x, y) +
  geom_smooth(method = "lm", formula = y ~ I(x^2)) + 
  geom_point() + 
  theme_bw()
```

